// packages/react/lib/RouterOutlet.tsx
import React, {
  PropsWithChildren,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState
} from 'react';
import Router from '@easyroute/core';
import { EasyrouteContext } from './EasyrouteContext';
import { getTransitionDurations } from '@easyroute/core/utils/getTransitionDurations';
import { isBrowser } from '@easyroute/core/utils/isBrowser';
import { RouteMatchData } from '@easyroute/core/dist/types';
import componentChangeWithTransition from '@easyroute/core/utils/componentChangeWithTransition';

interface RouterOutletProps {
  router?: Router;
  transition?: string;
  forceRemount?: boolean;
  className?: string;
  name?: string;
}

const SSR_CONTEXT = !isBrowser();

export const RouterOutlet = (props: PropsWithChildren<RouterOutletProps>) => {
  const { router, nestingDepth } = useContext(EasyrouteContext);
  const [component, setComponent] = useState<any>('');
  const [prevRouteId, setPrevRouteId] = useState<string | null>(null);
  const [transitionClassName, setTransitionClassName] = useState('');
  const name = props.name ?? 'default';
  const { forceRemount, transition, className } = props;
  const transitionData = SSR_CONTEXT
    ? null
    : props.transition
    ? getTransitionDurations(props.transition)
    : null;

  if (!router || nestingDepth === undefined) {
    throw new Error(
      '[Easyroute] RouterOutlet: no router instance found. Did you forget to wrap your ' +
        'root component with <EasyrouteProvider>?'
    );
  }

  const changeComponent = useCallback(
    async (
      Component: any,
      isClassComponent: boolean,
      currentRoute: RouteMatchData
    ) => {
      const componentProps = {
        router,
        currentRoute: router.currentRoute
      };
      if (prevRouteId === currentRoute.id && !forceRemount) return;
      const distComponent = isClassComponent ? (
        Component.render(componentProps)
      ) : (
        <Component {...componentProps} />
      );
      if (!transitionData) {
        if (Component === '') {
          setComponent('');
        } else {
          setComponent(distComponent);
        }
      } else {
        componentChangeWithTransition(
          distComponent,
          currentRoute,
          transition as string,
          (c: string) => setTransitionClassName(c),
          (c: any) => setComponent(c),
          router,
          transitionData
        );
      }
      setPrevRouteId(currentRoute.id);
    },
    []
  );

  const matchedSubscribe = useCallback(
    async (matchedRoutes: RouteMatchData[]) => {
      const componentProps = {
        router,
        currentRoute: router.currentRoute
      };

      const currentRoute = matchedRoutes.find(
        (route) => route.nestingDepth === nestingDepth
      );
      if (currentRoute) {
        let componentValue;
        if (name === 'default')
          componentValue =
            currentRoute.component || currentRoute.components?.default;
        else
          componentValue = currentRoute.components
            ? currentRoute.components[name]
            : null;
        if (!componentValue) {
          await changeComponent('', false, currentRoute);
          return;
        }
        const Component = componentValue;
        const isClassComponent = !!Component?.prototype?.render;
        const preparedComponent = isClassComponent
          ? new Component(componentProps)
          : Component;
        try {
          await changeComponent(
            preparedComponent,
            isClassComponent,
            currentRoute
          );
        } catch (e) {
          setComponent(`[Easyroute] Error changing component: ${e.message}`);
        }
      } else {
        setComponent('');
      }
    },
    []
  );

  if (SSR_CONTEXT) {
    matchedSubscribe(router.currentMatched.getValue);
  }

  useEffect(() => {
    if (SSR_CONTEXT) return () => {};
    const unsubscribe = router.currentMatched.subscribe(matchedSubscribe);
    return () => unsubscribe();
  }, []);

  const classList = useMemo(() => {
    const classListArray = ['easyroute-outlet'];
    className && classListArray.push(className);
    transitionClassName && classListArray.push(transitionClassName);
    return classListArray.join(' ');
  }, [transitionClassName, className]);

  const componentProps = {
    router,
    currentRoute: router.currentRoute
  };

  return (
    <EasyrouteContext.Provider
      value={{ router, nestingDepth: nestingDepth + 1 }}
    >
      <div className={classList}>{component}</div>
    </EasyrouteContext.Provider>
  );
};

// packages/svelte/lib/RouterOutlet.svelte
<script>
    import { setContext, getContext, onDestroy, onMount } from 'svelte';
    import { getTransitionDurations } from '@easyroute/core/utils/getTransitionDurations';
    import { delay } from '@easyroute/core/utils/delay';
    import { isBrowser } from '@easyroute/core/utils/isBrowser';
    import componentChangeWithTransition from '@easyroute/core/utils/componentChangeWithTransition';

    export let transition = null, forceRemount = false, name = 'default';

    const SSR_CONTEXT = !isBrowser();
    const context = getContext('easyrouteContext');
    const depth = context ? context.depth + 1 || 0 : 0;
    const router = context ? context.router : null;
    const transitionData = SSR_CONTEXT ?
        null :
        transition ?
            getTransitionDurations(transition) :
            null;
    let prevRouteId = null;
    let currentComponent = null;
    let transitionClassName = '';
    let firstRouteResolved = SSR_CONTEXT
    let unsubscribe = null

    if (!router) {
        throw new Error('[Easyroute] RouterOutlet: no router instance found. Did you forget to wrap your ' +
            'root component with <EasyrouteProvider>?');
    }
    setContext('easyrouteContext', { depth, router });

    async function changeComponent(component, currentRoute) {
        if (prevRouteId === currentRoute.id && !forceRemount) return;
        if (!transitionData) {
            currentComponent = component;
        } else {
            await componentChangeWithTransition(
                component,
                transition,
                tcn => transitionClassName = tcn,
                c => currentComponent = c,
                router,
                transitionData
            );
        }
        prevRouteId = currentRoute.id
    }

    async function pickRoute(routes) {
        const currentRoute = routes.find(route => route.nestingDepth === depth);
        if (currentRoute) {
            let component;
            if (name === 'default') component = currentRoute.component || currentRoute.components.default;
            else component = currentRoute.components ? currentRoute.components[name] : null;
            changeComponent(component, currentRoute);
            await delay(transitionData ? transitionData.leavingDuration : 0);
            firstRouteResolved = true;
        } else {
            changeComponent(null, `${Date.now()}-nonexistent-route`);
        }
    }

    onMount(() => {
        if (!SSR_CONTEXT) {
            unsubscribe = router.currentMatched.subscribe(routes => pickRoute(routes));
        }
    });

    onDestroy(() => {
        unsubscribe && unsubscribe();
    });

    SSR_CONTEXT && pickRoute(router.currentMatched.getValue)
</script>

<div class:easyroute-outlet class={$$restProps.class + ' ' + transitionClassName}>
    {#if firstRouteResolved}
        <svelte:component this={currentComponent} router={router} />
    {/if}
</div>
