// packages/svelte/lib/RouterLink.svelte

<script>
    import { getContext } from 'svelte'
    export let to;
    const context = getContext('easyrouteContext')
    const router = context ? context.router : null
    const attrs = Object.assign({}, $$props)
    if (!router) {
        throw new Error('[Easyroute] RouterLink: no router instance found. Did you forget to wrap your ' +
            'root component with <EasyrouteProvider>?')
    }
    function routerNavigate(evt) {
        evt.preventDefault()
        evt.stopPropagation()
        if (!router) {
            throw new Error('[Easyroute] Router instance not found in RouterLink')
        }
        router.push(to)
    }
    function sanitizeAttrs() {
        delete attrs.to
        delete attrs.$$slots
        delete attrs.$$scope
    }
    sanitizeAttrs()
</script>

<a href={to} {...attrs} on:click={routerNavigate}>
    <slot />
</a>

// packages/react/lib/RouterLink.tsx
import React, { PropsWithChildren, useCallback, useContext } from 'react'
import { EasyrouteContext } from './EasyrouteContext'

interface RouterLinkProps {
  to: string
  className?: string
}

export const RouterLink = (props: PropsWithChildren<RouterLinkProps>) => {
  const { router } = useContext(EasyrouteContext)

  const routerNavigate = useCallback((evt: React.MouseEvent) => {
    evt.preventDefault()
    evt.stopPropagation()
    if (!router) {
      throw new Error('[Easyroute] Router instance not found in RouterLink')
    }
    const resultPath = props.to[0] === '/' ? props.to : `/${props.to}`
    router.push(resultPath).catch((err) => console.error(err))
  }, [])

  return (
    <a className={'router-link' + 'className'} href={props.to} onClick={routerNavigate}>
      {props.children}
    </a>
  )
}
